### ISSUE TITLE
Install validator on an Express Router

### ISSUE THREAD

**Issue by Aidenir** [cdimascio/express-openapi-validator#144]
We currently have a very large codebase and not everything is documented in our spec doc. So my idea was to introduce this into Routers instead, so we could introduce it on an endpoint basis gradually instead. But unless I install this on the actual app it doesn't appear to do anything what so ever. I've tried going through the code to find any reason for this, but as I'm somewhat new to express I can't find anything in particular that would prevent it from being installed on a router that is later installed on the app itself.

Other libraries allow you to just get the actual middleware function so you can add this yourself to the method handler, but this doesn't appear to be possible with this library either. Any reason for this?

**Comment by cdimascio** [comment]
The library must utilize express' `app.param([name], callback)` in order to ensure path params match those defined in your spec definition. unfortunately, this is only available at the app level and not to middleware functions. this is a key reason why the validator is not implemented as a traditional middleware function. 

that being said, i plan to introduce a feature that enables you to provide a regex that can be used to ignore routes. this should make it possible to still benefit from app params, yet also make it possible for devs (like yourself) to introduce the validator into a large project, where it's difficult to provide doc for all endpoints up front

**Comment by cdimascio** [comment]
This issue is related to Add ability to ignore validation on routes to avoid 404 status for undocumented routes #141
The assumption here is that by providing a mechanism to ignore validation on paths, we can make it possible to gradually introduce express-openapi-validator into a large codebase.

**Comment by cdimascio** [comment]
Closing this out as I believe #157 gives you what you need.
Please reopen if not the case.

**Comment by dash-xd** [comment]
hello there, the answer here doesn't actually solve the topic in the title. middleware needs to work at the router level, correct? i have a requirement where i need the validator at the router level and i deploy routers to a production express application that i do not have control over.

i have tried playing around with req.app.use() but i doubt that will work.

will there ever be actual middleware? otherwise i'll be maintaining different versions of the openapi spec (probably will use the PayU library which supports 3.0) for different projects and i might just push to switch off javascript at that point. alternatively i might switch to json schemas and ajv (reference them in the yaml spec), but i don't think that will scale for my multilang projects.

thanks for your time!
