### ISSUE TITLE
Handle typos in operationIds / missing handler better

### ISSUE THREAD

**Issue by joerg-walter-de** [cdimascio/express-openapi-validator#285]
A mismatch of operationIds (when autmatically mapped) and the actual handler functions doesn't yield  any usable error message. The name of the missing function / path etc. should be displayed.

**Comment by cdimascio** [comment]
hi @joerg-walter-de, are you using the latest version?

note that very recently pushed a couple of commits that improve the messaging around typos in operations. Here is the most recent of these commits.

https://github.com/cdimascio/express-openapi-validator/blob/master/src/index.ts#L264

let me know if upgrading to the latest solves your issue. if not perhaps you can provide a brief snippet so that I can repro it and provide a better experience

**Comment by cdimascio** [comment]
@joerg-walter-de sounds like the upgrade solved the issue? if not please reopen
