### ISSUE TITLE
TypeError: app.param is not a function

### ISSUE THREAD

**Issue by tannerntannern** [cdimascio/express-openapi-validator#365]
**Describe the bug**
All alpha releases of 4.0.0 appear to run into the following error: `TypeError: app.param is not a function`.  For previous alphas, this surfaced as an uncaught promise rejection, but `alpha.4` and `alpha.5` now catch this rejection and kill the request.

**To Reproduce**
I'm having difficulty reproducing this issue on a fresh repo and my time for these issues is limited while at work.  I can spend more time reproducing this later, but I do have a clue as to why this may be happening:

* The error appears to result from `app.param(` in [openapi.validator.ts#L171](https://github.com/cdimascio/express-openapi-validator/blob/v4/src/openapi.validator.ts#L171), because `app.param` is undefined.
* The signature of `installPathParams` ([L171](https://github.com/cdimascio/express-openapi-validator/blob/v4/src/openapi.validator.ts#L161)) appears to accept either `Application` or `Router` as its `app` parameter, but when I manually inserted a `console.log`, app appears to be a _`Route`_, not a _`Router`_
* This theory makes sense if you look at how `installPathParams` is called:  `this.installPathParams(req.route || req.app, context);` ([L93](https://github.com/cdimascio/express-openapi-validator/blob/v4/src/openapi.validator.ts#L93))
* Furthermore, if you look at the express typings for `Route`, you can confirm that there's no `param` field on the interface.

**Additional Context**
I'm using express-openapi-validator with an express router, rather than directly on an express app.  I apologize that I can't supply a minimum-reproducible-example at the moment.  Hopefully the bullets above should be enough to reveal the issue

**Comment by cdimascio** [comment]
@tannerntannern this is fixed in `v4.0.0-alpha.6`

note that there is one minor issue that can't be solved. when nested routers are added to e.g. `app` via `app.use('/api', router`. If a path parameter exists for a the route, `/api/pets/:id` where id is of type `number` e.g. `/api/pets/123`; `123` will be correctly validated/coerced as a number, however, in you terminal middleware function, `req.params.id` will be provide `id` as a `string` e.g. `'123'`. this will occur for nested routes. ultimately, it means the caller must coerce the param from `string` to necessary type e.g. `number`. This issue could be solved easily if express provided the current router within the handler function on req, res, or next e.g. `(req, res, next) => ...`. Unfortunately, express does not provide this info. To my knowledge, there is no way to infer that information from within a middleware function, hence we end up with this relatively minor issue, but still a nuisance.

**Comment by tannerntannern** [comment]
Thanks again for the quick work on this!  I think I may have noticed this path param issue you described earlier, but as you mention, the workaround is simple enough.
