### ISSUE TITLE
Coerce parameters on the route?

### ISSUE THREAD

**Issue by rabbitfufu** [cdimascio/express-openapi-validator#372]
Hello, I'm using the new v4 alpha.  This is a great module! 
I have a question...
I have noticed that type coercion works great for parameters that are defined in the query.
However parameters that are a part are the route seem not to be coerced.  For example, in my yaml file I have...

```
paths:
  /clients/{id}:
    get:
      parameters:
      - $ref: '#/components/parameters/PathId'

components:
  parameters:
    PathId:
      name: id
      description: Id
      required: true
      in: path
      schema:
        $ref: '#/components/schemas/Id'
  schemas:
    Id:
      type: integer
      minimum: 1
```

...however when I then reference this variable in my code, I see this:

`console.log(typeof req.params.id) // string
`
I am not sure if this is a bug or by design...  Could you clarify? 
Thanks so much!

**Comment by cdimascio** [comment]
@rabbitfufu tl/dr this is known and currently expected behavior. 

**Below is a description of the behavior today**

- The validator will validate the types of all path params for **all** routes using the types declared in your spec. Specifically, this includes routes associated with the top level express `app`, `router`, or nested `router`s. 
- In v4, the validator will coerce and **modify** the path params e.g. `req.params.your_param_name` to the type declared in the spec for all routes declared directly on the express `app`. 
- In v3, the validator will coerce and **modify** the path params e.g. `req.params.your_param_name` to the type declared in the spec for all routes declared directly on the express `app` or directly on the specified top level router.  
- For both `v3` and `v4`, nested routers will be coerced and validation time, but will not be **modified**. 

What does modified mean? 

The validator updates value of `req.params.id` to the appropriate type. Thus, once your handler function is invoked each value in `req.params` is of the to the expected type (as declared in the spec).

In cases, where the value is not modified, your handler will receive each value in `req.params` as a string, not the declared type. Ultimately, you as the dev has to coerce it e.g. `parseInt(req.params.id)` :(

**Here's why this is the case**

In order for the validator to modify the `req.params`, express requires that you register a param handler via `app.param` or `router.param`. The validator always does this for `app` (Additionally, in v3, it can do this for a top level router that is passed to `install(...)`. The validator cannot do this for nested routers because express provides no mechanism to determine the current router. Because, of this, the validator can ensure the appropriate type at validation time, but cannot modify the `req.params` object.

**Are there any alternatives?**
Yes, we could potentially require developers to manually register a param handler for each route. IMO, this provides a poorer, more complex experience, when compared to a developer simply casting the value to the appropriate type themselves e.g. `parseInt(req.params.id)`

All in all, it's not ideal, perhaps express 5 (whenever that arrives) will provide a better mechanism to determine the router context. 

i'll work this information into the FAQ on the README

**Comment by rabbitfufu** [comment]
Hey Carmine, appreciate the detailed response.  Not a big deal to manually coerce them on my end.  Thanks for this great library, its been very helpful to me.
