### ISSUE TITLE
Custom handling of response validation error

### ISSUE THREAD

**Issue by nampas** [cdimascio/express-openapi-validator#454]
**Is your feature request related to a problem? Please describe.**
I'd like to enable response validation in an express app, but I don't want response validation to actually fail the request. In our case, a response validation error likely indicates that we haven't updated our openapi spec correctly. I'd like to log an error, but still return a 200 with the original response.

**Describe the solution you'd like**
It'd be great if there was some option in `validateResponses` to support this, perhaps an `onError` handler that would be invoked if provided instead of the default behavior of throwing.

**Describe alternatives you've considered**
There are probably some shenanigans I could do with re-munging `response.json()`, so that I catch any errors the validator throws. That doesn't seem ideal or straightforward.
Another option is to expose the validators themselves, so that I can call them in my own custom middleware, and handle errors accordingly. This is essentially what we were previously doing with express-openapi-validate, though we've had to abandon that library due to a lack of support for `$ref`s.

**Comment by cdimascio** [comment]
interesting idea. will consider it

**Comment by cdimascio** [comment]
@nampas please feel empowered to implement your idea. i'm happy to review, comment, etc.

Here's a tip to get you started... you will basically need to push an option through to the response validator. then ultimately when the response validation middleware encounters a validation error, it throws  [here](https://github.com/cdimascio/express-openapi-validator/blob/master/src/middlewares/openapi.response.validator.ts#L169). You'll want to customize this behavior. Instead of throwing, invoke a some function that is registered with the `validationResponses` option and return `next()`. 

Some thought is certainly needed around what the function might look like and what a user is expected to implement.
But all in all, this will get you started.

**Comment by nampas** [comment]
Ok thanks @cdimascio . I took a quick stab at it, let me know if you think I'm on the right track.
https://github.com/cdimascio/express-openapi-validator/pull/456

**Comment by cdimascio** [comment]
@nampas closing this out. i believe this is now resolved by your PR #456.
