### ISSUE TITLE
Type definition of OpenApiRequest has issue

### ISSUE THREAD

**Issue by gcohler** [cdimascio/express-openapi-validator#460]
In src/framework/types.ts, the definition of OpenApiRequest is rejected by typescript because of the `| {}` in its definition.  My suggestion is to remove the `| {}` altogether -- as the ? makes the openapi property optional already.  That makes it parse correctly in typescript.

Error message when referencing the .pathParams property of the OpenApiRequest variable:  ` error TS2339: Property 'pathParams' does not exist on type '{} | OpenApiRequestMetadata'`

Current code:

```
export interface OpenApiRequest extends Request {
  openapi?: OpenApiRequestMetadata | {};
}
```

Suggested change:

```
export interface OpenApiRequest extends Request {
  openapi?: OpenApiRequestMetadata;
}
```

**Comment by cdimascio** [comment]
@gcohler currently, the openapi property is either an empty object or OpenApiRequestMetadata.  It will be missing for routes that the validator does not impact. All in all, this type should be improved. 

This is a bit cumbersome and could certainly be cleaner.

All in all, I agree with your proposal. It should be optional. In order to make this change, a bit of code in openapi.metadata middleware needs to change to set nothing, rather than empty object. This may require some minor downstream changes for code that expectes empty.

In any case, agreed, let's fix it. It is slightly more involved than just marking it optional. 

Feel free to take a stab at it. I'm happy to review

**Comment by gcohler** [comment]
I submitted PR #462.  As I noted there, I'm not really expert enough on this to know if my change is sufficient.
