### ISSUE TITLE
body type string is not recognized

### ISSUE THREAD

**Issue by gonenduk** [cdimascio/express-openapi-validator#64]
When expecting a body parameter of type string (not a json!) - an error is returned saying the body parameter is not a string even if it is.
Bellow is a sample yaml code that shows it.
The references are for the definitions of the id param and the returned values (not relevant here).

```yaml
  /users/{id}/role:
    parameters:
    - $ref: '#/components/parameters/idParam'
    put:
      tags:
        - Users
      description: Set user role
      responses:
        '204':
          $ref: '#/components/responses/NoContentResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              enum:
                - user
                - moderator
                - admin
        description: New role
        required: true
```

**Comment by gonenduk** [comment]
Note: In the example above there is also an enum on the string value, but it can be removed for this sample. The issue is with the string type - not the enum.

**Comment by cdimascio** [comment]
@gonenduk Can you ensure you are able to parse body text

For example, ensure you're able to parser both text and json bodies with express. For example, you might use the bodyParser middlewares:

e.g. 

```javascript
app.use(bodyParser.text());
app.use(bodyParser.json());
```

i have a hunch that perhaps everything is parsed to json and thus the validator is getting `req.body` with an empty JSON value e.g. `{}`, rather than a string value e.g. `whatever string the call PUT`

assuming this is the case, the validator should throw some kind of validation error stating that it received `{}` instead of a string value (and perhaps a note about the body parser to help dev's sort the issue)

**Comment by gonenduk** [comment]
Thanks! That was the problem :)
In the code I added:
app.use(express.json());
app.use(express.text());

**Comment by cdimascio** [comment]
Fantastic! I added some notes to the README. Do you feel the validator should do more here, that is beyond some notes in the README it.

**Comment by gonenduk** [comment]
Not sure there is anything you can do in the validator in this case.
Maybe extend the error message after saying it should be a string, add the type you got - in my case i believe it was undefined (it was not a json and there was no parser for text so req.body left undefined)
maybe adding the typeof req.body to the error message info will help. But I'm not so sure about this.
