### ISSUE TITLE
Update path-to-regexp

### ISSUE THREAD

**Issue by klassm** [cdimascio/express-openapi-validator#966]
Please update to the current version of path-to-express, to mitigate the security vulnerability described in https://github.com/advisories/GHSA-9wv6-86v2-598j. Fix version should be 8.1.0

Thanks :-)!

**Comment by StevenCederrand** [comment]
`8.1.0` would also work.

**Comment by StevenCederrand** [comment]
`8.1.0` would probably be best, but yea, to remove the issue `8.0.0` is enough.

Please and thank you 🙌

**Comment by Alesyaa103** [comment]
v0.1.X also needs to be updated to v1.10.0

https://github.com/advisories/GHSA-9wv6-86v2-598j

**Comment by mmtdm** [comment]
currently this fails npm audit

```
npm install express-openapi-validator --save

added 120 packages, and audited 121 packages in 3s

17 packages are looking for funding
  run `npm fund` for details

2 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

ex % npm audit
# npm audit report

path-to-regexp  0.2.0 - 7.2.0
Severity: high
path-to-regexp outputs backtracking regular expressions - https://github.com/advisories/GHSA-9wv6-86v2-598j
No fix available
node_modules/express-openapi-validator/node_modules/path-to-regexp
  express-openapi-validator  *
  Depends on vulnerable versions of path-to-regexp
  node_modules/express-openapi-validator

2 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

```

**Comment by gauravrajpoot-wmp** [comment]
how to fix this issue. facing same problem

**Comment by avocadojesus** [comment]
The update is non-trivial, since newer versions of `path-to-regexp` don't support any of the tests in `test/wildcard.path.params.spec.ts` (except for the first test). Began working on this, but since I am not a regular contributor to this repo, I didn't feel I had the authority to decide not to support wildcard features, since technically express _does_ support them.

Express 4.20 is using `path-to-regexp@0.1.10`. I attempted to bring that version into this project as well, but it created 300+ test errors for me, so I defer to the package maintainers for the correct approach here.

To get to the point where only 7 wildcard specs are failing, you can bump `path-to-rexexp@8.0.1`, and then make the following changes:


<img width="957" alt="Screenshot 2024-09-11 at 11 00 21 AM" src="https://github.com/user-attachments/assets/e7e25649-0ab2-49fb-9a3b-ba57aa892a3e">
<img width="837" alt="Screenshot 2024-09-11 at 11 00 52 AM" src="https://github.com/user-attachments/assets/d3ca20ac-d171-4f10-bb7e-8f16e9ce6309">

Not sure what to do from there apart from just deleting the wildcard functionality, any ideas? Seems to me safest approach would be to go back to `path-to-regexp@0.1.10`, since express uses that version successfully to parse its routes, and it can handle the same wildcard expressions, but that results in massive failures and I don't have the time to look into them.

**Comment by cvchauhan** [comment]
for version 8.1.0 need to modify code as of now fix version is 6.3.0

**Comment by cdimascio** [comment]
The PR above upgrades to path-to-regex to 6.3.0 which resolvea the vulnerability. An upgrade to v8.x is still desired.  PRs welcome

**Comment by frankkeefer** [comment]
Found a way to update the code to support path-to-regexp 8.1.0 https://github.com/cdimascio/express-openapi-validator/pull/976. I had to do a pinch of rework in the openapi.spec.loader.ts to handle some of the new expectations for the 8.1.0 versions in setting up the path models.  If the PR needs any adjustments let me know.

**Comment by cvchauhan** [comment]
Yeah but after that change unit test also need to update more than 100 unit test we need to fix

**Comment by frankkeefer** [comment]
I did validate that the changes in #976 pass all the current unit tests.  I'm not sure what unit test updates would be needed beyond that.

**Comment by cvchauhan** [comment]
@frankkeefer  looks good thank you ☺️

**Comment by cvchauhan** [comment]
> The PR above upgrades to path-to-regex to 6.3.0 which resolves the vulnerability. An upgrade to v8.x is still desired. PRs welcome

https://github.com/cdimascio/express-openapi-validator/pull/975

**Comment by cvchauhan** [comment]
> Following the release of `path-to-regexp@6.3.0`, which is [patched](https://github.com/pillarjs/path-to-regexp/pull/324), `express-openapi-validator`'s [dependency on `path-to-regexp@^6.2.2`](https://github.com/cdimascio/express-openapi-validator/blob/772d1dcaae0104d12cf98d35168f1a7556b09b74/package.json#L48) should bring in a safe version of `path-to-regexp` by default. Downstream consumers are unblocked.

Pr has been raised already 
https://github.com/cdimascio/express-openapi-validator/pull/975

**Comment by dogmatic69** [comment]
Since https://github.com/cdimascio/express-openapi-validator/pull/976 is merged, can a new release be made? 🙏🏻

**Comment by cdimascio** [comment]
fixed. closing this out
